server:
  port: 9091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: xinput-client